import React, { useState, useMemo } from 'react';
import { usePlanner } from '../../context/PlannerContext';
import { generateWeeklyGroceryList, GroceryItem } from '../../services/groceryListEngine';
import { haptics } from '../../utils/haptics';

interface GroceryListModalProps {
  isOpen?: boolean;
  onClose: () => void;
}

export const GroceryListModal: React.FC<GroceryListModalProps> = ({ isOpen = true, onClose }) => {
  if (!isOpen) return null;

  const { store, showIsland } = usePlanner();
  const rawList = useMemo(() => generateWeeklyGroceryList(store.user), [store.user]);

  const [checkedMap, setCheckedMap] = useState<Record<string, boolean>>({});
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [copySuccess, setCopySuccess] = useState(false);

  const toggleCheck = (id: string) => {
    haptics.tap();
    setCheckedMap((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const categories = [
    { id: 'all', label: 'All Items', icon: '🛒', count: rawList.totalItems },
    { id: 'produce', label: 'Produce', icon: '🥬', count: rawList.produce.length },
    { id: 'protein', label: 'Proteins & Dairy', icon: '🧀', count: rawList.protein.length },
    { id: 'grains', label: 'Grains & Flours', icon: '🌾', count: rawList.grains.length },
    { id: 'superfoods', label: 'Superfoods & Seeds', icon: '🥑', count: rawList.superfoods.length },
    { id: 'pantry', label: 'Pantry & Spices', icon: '🧂', count: rawList.pantry.length }
  ];

  const getFilteredItems = (): { category: string; icon: string; items: GroceryItem[] }[] => {
    const list = [];
    if (selectedCategory === 'all' || selectedCategory === 'produce') {
      if (rawList.produce.length > 0) list.push({ category: 'Fresh Produce & Vegetables', icon: '🥬', items: rawList.produce });
    }
    if (selectedCategory === 'all' || selectedCategory === 'protein') {
      if (rawList.protein.length > 0) list.push({ category: 'Proteins, Dals & Dairy', icon: '🧀', items: rawList.protein });
    }
    if (selectedCategory === 'all' || selectedCategory === 'grains') {
      if (rawList.grains.length > 0) list.push({ category: 'Whole Grains & Flours', icon: '🌾', items: rawList.grains });
    }
    if (selectedCategory === 'all' || selectedCategory === 'superfoods') {
      if (rawList.superfoods.length > 0) list.push({ category: 'Seeds, Nuts & Superfoods', icon: '🥑', items: rawList.superfoods });
    }
    if (selectedCategory === 'all' || selectedCategory === 'pantry') {
      if (rawList.pantry.length > 0) list.push({ category: 'Pantry Essentials & Spices', icon: '🧂', items: rawList.pantry });
    }
    return list;
  };

  const filteredSections = getFilteredItems();
  const checkedCount = Object.values(checkedMap).filter(Boolean).length;
  const progressPct = rawList.totalItems > 0 ? Math.round((checkedCount / rawList.totalItems) * 100) : 0;

  // Format clean copy-paste text for WhatsApp / Notes
  const handleCopyClipboard = () => {
    haptics.medium();
    const goalTitle = (store.user.goal || 'Wellness').replace('_', ' ').toUpperCase();

    let text = `🛒 *HEALTHYHABITS 7-DAY GROCERY LIST*\n`;
    text += `🎯 Protocol: ${goalTitle} • 7-Day Plan\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━\n\n`;

    filteredSections.forEach((section) => {
      text += `${section.icon} *${section.category.toUpperCase()}*\n`;
      section.items.forEach((item) => {
        const checkMark = checkedMap[item.id] ? '✅' : '▫️';
        text += `${checkMark} ${item.name} (${item.weeklyQuantity})\n`;
      });
      text += `\n`;
    });

    text += `━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `✨ Generated by HealthyHabits Personalized Wellness Protocol`;

    if (navigator.clipboard) {
      navigator.clipboard.writeText(text);
      setCopySuccess(true);
      showIsland('📋 7-Day Grocery list copied for WhatsApp / Notes!');
      setTimeout(() => setCopySuccess(false), 3000);
    }
  };

  const checkAllVisible = () => {
    haptics.tap();
    const newMap = { ...checkedMap };
    filteredSections.forEach((s) => {
      s.items.forEach((item) => {
        newMap[item.id] = true;
      });
    });
    setCheckedMap(newMap);
  };

  const clearAllChecked = () => {
    haptics.tap();
    setCheckedMap({});
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.65)',
        backdropFilter: 'blur(16px)',
        WebkitBackdropFilter: 'blur(16px)',
        zIndex: 4000,
        display: 'flex',
        alignItems: 'flex-end',
        justifyContent: 'center'
      }}
      onClick={onClose}
    >
      <div
        className="slide-up"
        style={{
          width: '100%',
          maxWidth: '480px',
          background: 'var(--surface-solid)',
          borderTopLeftRadius: '32px',
          borderTopRightRadius: '32px',
          padding: '22px 20px 35px',
          maxHeight: '88dvh',
          display: 'flex',
          flexDirection: 'column',
          boxShadow: '0 -15px 45px rgba(0, 0, 0, 0.4)',
          borderTop: '1px solid var(--border-glass)'
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="sheet-drag-handle" style={{ marginBottom: '14px' }} />

        {/* Header Row */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '10px' }}>
          <div>
            <div style={{ fontSize: '0.72rem', fontWeight: 800, color: 'var(--primary)', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              7-Day Weekly Meal Prep
            </div>
            <h3 style={{ margin: '2px 0 0 0', fontSize: '1.3rem', fontWeight: 900, color: 'var(--text-1)' }}>
              🛒 Smart Grocery Checklist
            </h3>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <button
              onClick={handleCopyClipboard}
              style={{
                background: copySuccess ? '#34C759' : 'var(--primary-dim)',
                border: 'none',
                color: copySuccess ? '#ffffff' : 'var(--primary)',
                padding: '7px 14px',
                borderRadius: '14px',
                fontSize: '0.75rem',
                fontWeight: 800,
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '4px',
                transition: 'all 0.2s ease'
              }}
            >
              <span>{copySuccess ? '✓ Copied' : '📋 Copy for WhatsApp'}</span>
            </button>

            <button
              onClick={onClose}
              style={{
                background: 'var(--border)',
                border: 'none',
                borderRadius: '50%',
                width: '32px',
                height: '32px',
                cursor: 'pointer',
                fontWeight: 800,
                color: 'var(--text-1)'
              }}
            >
              ✕
            </button>
          </div>
        </div>

        {/* Progress Bar & Counter */}
        <div
          style={{
            background: 'var(--surface-2)',
            border: '1px solid var(--border-glass)',
            borderRadius: '18px',
            padding: '10px 14px',
            marginBottom: '12px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between'
          }}
        >
          <div style={{ flex: 1, paddingRight: '12px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', fontWeight: 800, color: 'var(--text-2)', marginBottom: '4px' }}>
              <span>Shopping Cart Progress</span>
              <span style={{ color: 'var(--primary)' }}>{checkedCount} / {rawList.totalItems} items ({progressPct}%)</span>
            </div>
            <div style={{ width: '100%', height: '6px', background: 'var(--border)', borderRadius: '4px', overflow: 'hidden' }}>
              <div
                style={{
                  width: `${progressPct}%`,
                  height: '100%',
                  background: progressPct === 100 ? '#34C759' : 'linear-gradient(90deg, var(--primary), #30D158)',
                  borderRadius: '4px',
                  transition: 'width 0.3s ease'
                }}
              />
            </div>
          </div>

          <div style={{ display: 'flex', gap: '4px' }}>
            <button
              onClick={checkAllVisible}
              style={{
                background: 'transparent',
                border: 'none',
                color: 'var(--primary)',
                fontSize: '0.7rem',
                fontWeight: 800,
                cursor: 'pointer',
                padding: '4px'
              }}
            >
              Check All
            </button>
            <span style={{ color: 'var(--text-3)', fontSize: '0.7rem' }}>•</span>
            <button
              onClick={clearAllChecked}
              style={{
                background: 'transparent',
                border: 'none',
                color: 'var(--text-2)',
                fontSize: '0.7rem',
                fontWeight: 800,
                cursor: 'pointer',
                padding: '4px'
              }}
            >
              Reset
            </button>
          </div>
        </div>

        {/* Category Filter Pills */}
        <div
          style={{
            display: 'flex',
            gap: '8px',
            overflowX: 'auto',
            paddingBottom: '8px',
            marginBottom: '8px'
          }}
        >
          {categories.map((c) => (
            <button
              key={c.id}
              onClick={() => {
                haptics.tap();
                setSelectedCategory(c.id);
              }}
              style={{
                background: selectedCategory === c.id ? 'var(--primary)' : 'var(--surface)',
                color: selectedCategory === c.id ? '#ffffff' : 'var(--text-2)',
                border: '1px solid var(--border-glass)',
                padding: '6px 12px',
                borderRadius: '14px',
                fontSize: '0.72rem',
                fontWeight: 800,
                whiteSpace: 'nowrap',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '4px',
                flexShrink: 0,
                transition: 'all 0.2s cubic-bezier(0.34, 1.56, 0.64, 1)'
              }}
            >
              <span>{c.icon}</span>
              <span>{c.label}</span>
              <span style={{ opacity: 0.75 }}>({c.count})</span>
            </button>
          ))}
        </div>

        {/* Categorized Checklist Items */}
        <div style={{ flex: 1, overflowY: 'auto', paddingRight: '2px' }}>
          {filteredSections.map((section) => (
            <div key={section.category} style={{ marginBottom: '14px' }}>
              <div
                style={{
                  fontSize: '0.75rem',
                  fontWeight: 800,
                  textTransform: 'uppercase',
                  color: 'var(--primary)',
                  marginBottom: '8px',
                  letterSpacing: '0.5px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px'
                }}
              >
                <span>{section.icon}</span>
                <span>{section.category}</span>
                <span style={{ fontSize: '0.7rem', color: 'var(--text-3)', fontWeight: 600 }}>
                  ({section.items.length} items)
                </span>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {section.items.map((item) => {
                  const isChecked = !!checkedMap[item.id];
                  return (
                    <div
                      key={item.id}
                      onClick={() => toggleCheck(item.id)}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        padding: '12px 14px',
                        borderRadius: '18px',
                        background: isChecked ? 'var(--surface-2)' : 'var(--surface)',
                        border: isChecked ? '1px solid rgba(52, 199, 89, 0.3)' : '1px solid var(--border-glass)',
                        cursor: 'pointer',
                        transition: 'all 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
                        opacity: isChecked ? 0.65 : 1
                      }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                        <div
                          style={{
                            width: '22px',
                            height: '22px',
                            borderRadius: '8px',
                            border: isChecked ? 'none' : '2px solid var(--border-glass)',
                            background: isChecked ? '#34C759' : 'var(--surface-2)',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            color: '#ffffff',
                            fontSize: '0.8rem',
                            fontWeight: 900,
                            boxShadow: isChecked ? '0 0 10px rgba(52, 199, 89, 0.4)' : 'none',
                            transition: 'all 0.2s ease'
                          }}
                        >
                          {isChecked && '✓'}
                        </div>

                        <div>
                          <div
                            style={{
                              fontSize: '0.9rem',
                              fontWeight: 800,
                              color: 'var(--text-1)',
                              textDecoration: isChecked ? 'line-through' : 'none'
                            }}
                          >
                            {item.name}
                          </div>
                          <div style={{ fontSize: '0.7rem', color: 'var(--text-2)', marginTop: '1px' }}>
                            For: {item.mealsUsedIn.join(', ')}
                          </div>
                        </div>
                      </div>

                      <span
                        style={{
                          fontSize: '0.75rem',
                          fontWeight: 800,
                          color: isChecked ? 'var(--text-3)' : 'var(--primary)',
                          background: isChecked ? 'var(--border)' : 'var(--primary-dim)',
                          padding: '4px 8px',
                          borderRadius: '8px',
                          flexShrink: 0
                        }}
                      >
                        {item.weeklyQuantity}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
